Eb 78 change logo
DHBW-Easy-Board/easy_board_application pull request #18
Opened 2023-05-02 18:10 UTC by Hesoyam01

2023-05-02 20:29 UTC, J-C-V requested changes
Please implement a component (board-logo) which just loads and displays the board image as small logo with a given board id, so that we can easily display a board logo anywhere in the app.

2023-05-02 20:29 UTC, J-C-V commented on src/app/features/kanban/components/upload-image/upload-image.component.html
Pls give your component some sort of form - Right now it's just a row:

![image](https://user-images.githubusercontent.com/12070160/235771499-1bcd559b-c5a7-42ab-961d-26f815fbed46.png)

Maybe something like this, but feel free to adjust it yourself:

![image](https://user-images.githubusercontent.com/12070160/235778589-ee5bff14-797c-4840-a3ce-88b099efd4f6.png)

- Upload button isn't recognizable as button (Give it at least primary color)
- We use English as ui language

2023-05-02 20:29 UTC, J-C-V commented on src/app/features/kanban/components/upload-image/upload-image.component.ts
- Please add comments on what your methods are doing (Is needed for submitting the documentation...)
- Specify for the user which file types are supported (line 78)

2023-05-03 09:27 UTC, Hesoyam01 commented on src/app/shared/components/nav-bar/nav-bar.component.html
done

2023-05-03 09:28 UTC, Hesoyam01 commented on src/app/features/kanban/components/upload-image/upload-image.component.ts
@J-C-V The select file dialog only lets you select the specified type

2023-05-03 09:51 UTC, Hesoyam01 commented on src/app/features/kanban/components/upload-image/upload-image.component.ts
done

2023-05-03 09:59 UTC, Hesoyam01 commented on src/app/features/kanban/components/upload-image/upload-image.component.html
language browser specific.

2023-05-03 10:49 UTC, Hesoyam01 commented on src/app/features/kanban/components/upload-image/upload-image.component.html
done

2023-05-03 15:08 UTC, J-C-V approved these changes
@Hesoyam01 Current branch gets merged. Please make a new pull request for the missing board-logo component.

2023-05-03 15:08 UTC, merged