Eb 45 change profile data
DHBW-Easy-Board/easy_board_application pull request #8
Opened 2023-04-13 18:06 UTC by Hesoyam01

2023-04-15 16:47 UTC, J-C-V requested changes
see comments

2023-04-15 16:47 UTC, J-C-V commented on src/app/features/user/components/edit-dialog/edit-dialog.component.ts
- remove debug console.log
- remove unused code (currently commented out)
- dont sign out user after changing email or password successfully

2023-04-15 16:47 UTC, J-C-V commented on src/app/features/user/pages/profile/profile.component.html
- why is email an a? just move the current email in the edit email dialog
- maybe flex order column and buttons full width instead?

2023-04-15 16:47 UTC, J-C-V commented on src/app/features/user/pages/profile/profile.component.scss
- remove unused code

2023-04-15 18:04 UTC, J-C-V commented
also add some sort of feedback for the user - if change was successful or not

2023-04-19 16:24 UTC, Hesoyam01 commented
@J-C-V ready to merge

2023-04-19 18:41 UTC, J-C-V requested changes
See comment

2023-04-19 18:59 UTC, J-C-V commented on src/app/features/user/components/edit-dialog/edit-dialog.component.html
- Switch confirm/cancel button position

2023-04-25 09:58 UTC, J-C-V requested changes
See comments

2023-04-26 06:14 UTC, J-C-V approved these changes
LGTM

2023-04-26 06:21 UTC, merged